FROM node:16-alpine as build-step

WORKDIR /usr/src/app

RUN npm i -g @quasar/cli

RUN npm install -g npm@9.2.0

COPY package*.json /usr/src/app/

COPY src /usr/src/app/src/
COPY public /usr/src/app/public/
COPY . /usr/src/app/

RUN npm install

RUN quasar build

FROM nginx:stable-alpine as production

COPY --from=build-step /usr/src/app/dist/spa /usr/share/nginx/html
COPY nginx.default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443

CMD [ "nginx", "-g", "daemon off;"]
